Readme update
alat-rights/alana-utilities pull request #24
Opened 2024-04-27 10:13 UTC by Domejko

Added **Contributing** section to `README.md`

2024-04-27 10:42 UTC, alat-rights commented
Thanks for making the PR.

Nits:
1. We should mention that we use the [Standard](https://github.com/microsoft/pyright/issues/6607) mode on PyRight.
2. I would probably do without the preamble. It's not a great fit for a project of this (small) size.

BTW: I think this project will have more detailed workflow soon. E.g. I think I'm going to have separate `dev` and `release` branches. There will be some focus on making the project stable.

For future reference: the more minimal a PR is, the easier it is for us to get it merged.

2024-04-27 11:34 UTC, alat-rights commented
#21

2024-04-29 11:41 UTC, Domejko commented
> 1. We should mention that we use the [Standard](https://github.com/microsoft/pyright/issues/6607) mode on PyRight.

But there is no flag to differentiate `basic/standard/strict` and we are not using neither `pyproject.toml` or `pyrightconfig.json` for configuration, so it's used with default settings. Then I think it's not necessary to mention it.



> 2\. I would probably do without the preamble. It's not a great fit for a project of this (small) size.

I will reduce it to simple greeting then. To be nice and welcoming is always good.

2024-04-29 13:00 UTC, alat-rights requested changes
Should be good with these changes.

2024-04-29 13:00 UTC, alat-rights commented on docs/README.md
> +A big welcome and thank you for considering contributing to alana-utilities open source project!
```suggestion
Welcome! Thank you for considering making a contribution to `alana-utilities`.
```

2024-04-29 13:00 UTC, alat-rights commented on docs/README.md
> +For changes that address core functionality or would require breaking changes (e.g. a major release), it's best to open an Issue to discuss your proposal first. This is not required but can save time
```suggestion
If you'd like to make a major refactor or breaking change, please open an [Issue](https://github.com/alat-rights/alana-utilities/issues) first. This way, I can review it to determine if it is within scope for this project.

In general, there are no guarantees that your pull requests will be merged into the library. `alana-utilities` is essentially a hobby project, and there is currently only one maintainer.
```

2024-04-29 13:00 UTC, alat-rights commented on docs/README.md
> +Before pushing your code and making PR make sure that you have run `black .` on your code, otherwise it will fail.
```suggestion
Before submitting a pull request, please run `black .` on your code. This saves us from failed CI runs.
```

2024-04-29 13:00 UTC, alat-rights commented on docs/README.md
> +To install and run black use this commands:
```suggestion
To install and run `Black`:
```

2024-04-29 13:00 UTC, alat-rights commented on docs/README.md
> +To keep types in code consistent:
```suggestion
To install and run `PyRight`:
```

2024-04-29 13:29 UTC, alat-rights submitted a review, later dismissed
Just caught a few more minor things :)

2024-04-29 13:29 UTC, alat-rights commented on docs/README.md
> +In general, there are no guarantees that your pull requests will be merged into the library. `alana-utilities` is essentially a hobby project, and there is currently only one maintainer.
```suggestion
There are no guarantees that your pull requests will be merged into the library. `alana-utilities` is essentially a hobby project, and there is currently only one maintainer.

```

2024-04-29 13:29 UTC, alat-rights commented on docs/README.md
> +To install and run `PyRight`:
```suggestion

To install and run `PyRight`:
```

2024-04-29 13:29 UTC, alat-rights commented on docs/README.md
> +We are using [Black](https://github.com/psf/black) for formating and [PyRight](https://github.com/microsoft/pyright) for type checking.
```suggestion
We are using [Black](https://github.com/psf/black) for formatting and [PyRight](https://github.com/microsoft/pyright) for type checking.
```

2024-04-29 13:29 UTC, alat-rights commented on docs/README.md
> +To install and run `Black`:
```suggestion

To install and run `Black`:
```

2024-04-29 14:33 UTC, merged